#!/usr/bin/env php
<?php
declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';

chdir(__DIR__);

use Symfony\Component\Console\Application;

container()->bind('database', Lib\Database::class, true);

$application = new Application('Crawler', '1.0');

$application->add(new Lib\Commands\CrawlCommand());

$application->run();
